name: Generate INO File List

on:
  push:
    paths:
      - '**.ino'  # Only trigger when .ino files change

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate README with .ino files
        run: |
          # Create/overwrite README.md
          echo "# Arduino Project" > README.md
          echo "## List of .ino Files" >> README.md
          echo "This repository contains the following Arduino sketches:" >> README.md
          echo "" >> README.md
          
          # Find all .ino files (excluding .git directory)
          find . -name "*.ino" -not -path "./.git/*" | while read file; do
            echo "- [\`${file}\`](${file})" >> README.md
          done

      - name: Commit and Push README
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with .ino files [skip ci]" || echo "No changes"
          git push
